import { FormEvent, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { euro } from '../data/products';
import { AppHeader, EmptyState } from './components';
import { loadOrders } from './CartContext';

export function OrdersPage() { const orders = loadOrders(); return <><AppHeader/><main className="max-w-2xl mx-auto px-4 pt-6 pb-28"><h1 className="font-black text-4xl">Mis pedidos</h1>{orders.length ? <div className="mt-6 space-y-3">{orders.map((order) => <Link key={order.id} to={'/app/pedido/'+order.id} className="block border-2 border-ya-gray p-4 hover:border-ya-lime"><div className="flex justify-between font-black"><span>{order.id}</span><span>{euro(order.total)}</span></div><p className="text-sm text-gray-400 mt-1">{new Date(order.createdAt).toLocaleDateString('es-ES')} · {order.lines.reduce((sum,line)=>sum+line.quantity,0)} productos</p><p className="text-ya-lime text-sm font-bold mt-3">VER SEGUIMIENTO →</p></Link>)}</div> : <div className="mt-8"><EmptyState title="Todavía no hay pedidos" text="Cuando hagas uno aparecerá aquí."/></div>}</main></>; }
export function ProfilePage() { return <><AppHeader/><main className="max-w-2xl mx-auto px-4 pt-6 pb-28"><div className="bg-ya-lime text-ya-black p-5 border-2 border-ya-lime"><p className="font-bold uppercase text-sm">Tu perfil</p><h1 className="font-black text-4xl">Alex de YA</h1><p className="font-bold mt-2">hola@ya.app · +34 600 123 456</p></div><div className="mt-6 border-2 border-ya-gray divide-y-2 divide-ya-gray">{[['Mis pedidos','/app/pedidos'],['Mis direcciones','#'],['Métodos de pago','#']].map(([label,to]) => to==='#' ? <button key={label} className="w-full p-4 text-left font-black hover:bg-ya-gray">{label}<span className="float-right">→</span></button> : <Link key={label} to={to} className="block p-4 font-black hover:bg-ya-gray">{label}<span className="float-right">→</span></Link>)}</div><Link to="/login" className="block mt-6 text-center p-4 border-2 border-ya-gray font-black hover:border-ya-lime">CERRAR SESIÓN (MOCK)</Link></main></>; }
function AuthForm({ register }: { register?: boolean }) { const navigate = useNavigate(); const [message,setMessage] = useState(''); const submit=(event:FormEvent)=>{event.preventDefault(); setMessage(register ? 'Cuenta creada. Bienvenido a YA.' : 'Sesión iniciada. Bienvenido de nuevo.'); setTimeout(()=>navigate('/app'),500);}; return <main className="max-w-md mx-auto px-4 pt-12 pb-10"><Link to="/" className="text-ya-lime font-black text-5xl tracking-tighter">YA</Link><p className="mt-4 text-sm font-bold text-gray-400">LO NECESITAS. LO TIENES.</p><h1 className="font-black text-4xl mt-8">{register ? 'Crea tu cuenta' : 'Entra en YA'}</h1><form onSubmit={submit} className="mt-6 space-y-3">{register && <label className="block font-bold text-sm">Nombre<input required className="block mt-1 w-full bg-ya-gray border-2 border-ya-gray focus:border-ya-lime outline-none p-3" /></label>}<label className="block font-bold text-sm">Email<input required type="email" className="block mt-1 w-full bg-ya-gray border-2 border-ya-gray focus:border-ya-lime outline-none p-3" /></label>{register && <label className="block font-bold text-sm">Teléfono<input required type="tel" className="block mt-1 w-full bg-ya-gray border-2 border-ya-gray focus:border-ya-lime outline-none p-3" /></label>}<label className="block font-bold text-sm">Contraseña<input required minLength={6} type="password" className="block mt-1 w-full bg-ya-gray border-2 border-ya-gray focus:border-ya-lime outline-none p-3" /></label>{register && <label className="block font-bold text-sm">Repite la contraseña<input required minLength={6} type="password" className="block mt-1 w-full bg-ya-gray border-2 border-ya-gray focus:border-ya-lime outline-none p-3" /></label>}{register && <label className="flex gap-2 text-sm font-bold"><input required type="checkbox" /> Acepto los términos y la privacidad.</label>}<button className="w-full bg-ya-lime text-ya-black p-4 font-black">{register?'CREAR CUENTA':'ENTRAR'}</button>{message && <p role="status" className="font-bold text-ya-lime">{message}</p>}</form><p className="mt-5 text-gray-400">{register?'¿Ya tienes cuenta? ':'¿No tienes cuenta? '}<Link className="text-ya-lime font-bold" to={register?'/login':'/registro'}>{register?'Entrar':'Crear cuenta'}</Link></p></main>; }
export function LoginPage(){ return <AuthForm/>; } export function RegisterPage(){ return <AuthForm register/>; }