import { useMemo, useState } from 'react';
import { ArrowRight, Search } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { categories, products, productById } from '../data/products';
import { AppHeader, CategoryCard, EmptyState, ProductCard, QuantitySelector } from './components';
import { useCart } from './CartContext';

export function AppHome() { const featured = products.slice(0, 4); return <><AppHeader/><main className="max-w-5xl mx-auto px-4 pt-6 pb-28"><p className="text-sm font-bold text-gray-400">ENTREGA EN JEREZ DE LA FRONTERA</p><h1 className="text-5xl sm:text-6xl font-black tracking-tighter leading-none mt-3">¿Qué <span className="text-ya-lime">necesitas?</span></h1><Link to="/app/buscar" className="mt-6 bg-ya-white text-ya-black border-2 border-ya-white flex items-center justify-between p-4 font-black hover:bg-ya-lime hover:border-ya-lime">BUSCAR PRODUCTOS <Search size={20}/></Link><section className="mt-8"><h2 className="font-black text-2xl">Categorías</h2><div className="grid grid-cols-3 sm:grid-cols-4 md:grid-cols-7 gap-2 mt-3">{categories.map((item) => <CategoryCard key={item.slug} slug={item.slug}/>)}</div></section><section className="mt-10"><div className="flex justify-between items-baseline"><h2 className="font-black text-3xl">Destacados</h2><Link to="/app/buscar" className="text-ya-lime font-black text-sm flex gap-1">VER TODO <ArrowRight size={16}/></Link></div><div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-4">{featured.map((item) => <ProductCard key={item.id} product={item}/>)}</div></section><section className="mt-10 bg-ya-lime text-ya-black p-5 border-2 border-ya-lime"><p className="font-bold uppercase text-sm">Para esta noche</p><h2 className="font-black text-4xl tracking-tighter mt-1">Frío. Rápido.<br/>Directo a tu puerta.</h2><Link to="/app/categoria/hielo" className="inline-block mt-5 bg-ya-black text-ya-lime px-4 py-3 font-black">VER HIELO →</Link></section></main></>; }
export function CategoryPage() { const { slug } = useParams(); const category = categories.find((item) => item.slug === slug); const items = products.filter((item) => item.category === slug); if (!category) return <><AppHeader back/><main className="p-4 pb-28 max-w-5xl mx-auto"><EmptyState title="Categoría no encontrada" text="Vuelve a la app para descubrir productos."/></main></>; return <><AppHeader back/><main className="max-w-5xl mx-auto px-4 pt-6 pb-28"><p className="text-5xl">{category.icon}</p><h1 className="font-black text-5xl tracking-tighter">{category.name}</h1><p className="text-gray-400 mt-2">{category.description}</p><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3 mt-7">{items.length ? items.map((item) => <ProductCard key={item.id} product={item}/>) : <EmptyState title="Sin productos" text="Muy pronto habrá novedades aquí."/>}</div></main></>; }
export function SearchPage() { const [query, setQuery] = useState(''); const result = useMemo(() => { const term = query.toLowerCase().trim(); return !term ? products : products.filter((item) => [item.name,item.category,item.description].join(' ').toLowerCase().includes(term)); }, [query]); return <><AppHeader/><main className="max-w-5xl mx-auto px-4 pt-6 pb-28"><h1 className="font-black text-4xl">Buscar</h1><label className="sr-only" htmlFor="search">Busca productos</label><div className="flex mt-5 border-2 border-ya-gray focus-within:border-ya-lime"><Search className="m-3 text-ya-lime"/><input id="search" autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Red Bull, snacks, hielo..." className="bg-ya-gray w-full p-3 font-bold outline-none"/></div><p className="mt-5 text-sm font-bold text-gray-400">{result.length} RESULTADOS</p>{result.length ? <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3 mt-3">{result.map((item) => <ProductCard key={item.id} product={item}/>)}</div> : <div className="mt-8"><EmptyState title="No encontramos eso" text="Prueba con otro nombre o categoría."/></div>}</main></>; }
export function ProductPage() { const { id } = useParams(); const product = productById(id ?? ''); const { lines, addToCart, increaseQuantity, decreaseQuantity } = useCart(); if (!product) return <><AppHeader back/><main className="p-4 pb-28 max-w-2xl mx-auto"><EmptyState title="Producto no encontrado" text="Puede que ya no esté disponible."/></main></>; const quantity = lines.find((line) => line.productId === product.id)?.quantity ?? 0; return <><AppHeader back/><main className="max-w-2xl mx-auto px-4 pt-6 pb-28"><div className="h-64 sm:h-80 bg-ya-gray border-2 border-ya-gray grid place-items-center text-9xl">{product.image}</div><p className="font-bold text-ya-lime uppercase tracking-widest text-xs mt-6">Disponible ahora</p><h1 className="font-black text-5xl tracking-tighter mt-2">{product.name}</h1><p className="font-black text-3xl mt-4">{new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(product.price)}</p><p className="text-gray-300 text-lg mt-5">{product.description}</p><div className="mt-8 flex gap-3 items-center">{quantity ? <QuantitySelector quantity={quantity} onAdd={() => increaseQuantity(product.id)} onRemove={() => decreaseQuantity(product.id)}/> : null}<button onClick={() => addToCart(product.id)} className="flex-1 min-h-12 bg-ya-lime text-ya-black font-black uppercase hover:bg-white">{quantity ? 'Añadir otra unidad' : 'Añadir al carrito'}</button></div></main></>; }