import { motion } from 'framer-motion';
import { ChevronLeft, Home, Search, ShoppingBag, UserRound, ClipboardList, Minus, Plus, MapPin, PackageOpen } from 'lucide-react';
import { Link, NavLink } from 'react-router-dom';
import { categories, euro } from '../data/products';
import type { OrderStatus, Product } from '../types/app';
import { useCart } from './CartContext';

export function AppHeader({ back }: { back?: boolean }) { const { count } = useCart(); return <header className="sticky top-0 z-30 bg-ya-black border-b-2 border-ya-gray"><div className="max-w-5xl mx-auto h-16 px-4 flex items-center justify-between"><div className="flex items-center gap-3">{back && <Link aria-label="Volver" to="/app" className="p-2 border-2 border-ya-gray hover:border-ya-lime"><ChevronLeft /></Link>}<Link to="/app" className="font-black text-4xl leading-none text-ya-lime tracking-tighter">YA</Link><span className="hidden sm:flex text-xs font-bold text-gray-300 items-center gap-1"><MapPin size={14} />Jerez</span></div><div className="flex gap-2"><Link to="/app/carrito" aria-label="Abrir carrito" className="relative p-2 border-2 border-ya-gray hover:border-ya-lime"><ShoppingBag /><span className="absolute -right-2 -top-2 min-w-5 h-5 px-1 text-center bg-ya-lime text-ya-black text-xs font-black leading-5">{count}</span></Link><Link to="/app/perfil" aria-label="Perfil" className="p-2 border-2 border-ya-gray hover:border-ya-lime"><UserRound /></Link></div></div></header>; }
export function BottomNav() { const nav = [[Home,'Inicio','/app'],[Search,'Buscar','/app/buscar'],[ShoppingBag,'Carrito','/app/carrito'],[ClipboardList,'Pedidos','/app/pedidos'],[UserRound,'Perfil','/app/perfil']] as const; return <nav className="fixed bottom-0 inset-x-0 z-30 bg-ya-black border-t-2 border-ya-gray pb-[env(safe-area-inset-bottom)]"><div className="max-w-md mx-auto grid grid-cols-5">{nav.map(([Icon,label,to]) => <NavLink end={to === '/app'} key={to} to={to} className={({isActive}) => 'min-h-16 flex flex-col items-center justify-center gap-1 text-[10px] font-bold ' + (isActive ? 'text-ya-lime bg-ya-gray' : 'text-gray-400')}><Icon size={20}/>{label}</NavLink>)}</div></nav>; }
export function QuantitySelector({ quantity, onAdd, onRemove }: { quantity: number; onAdd: () => void; onRemove: () => void }) { return <div className="flex items-center border-2 border-ya-gray w-fit"><button aria-label="Reducir cantidad" onClick={onRemove} className="p-2 hover:bg-ya-gray"><Minus size={16}/></button><span className="w-8 text-center font-black">{quantity}</span><button aria-label="Aumentar cantidad" onClick={onAdd} className="p-2 bg-ya-lime text-ya-black hover:bg-white"><Plus size={16}/></button></div>; }
export function ProductCard({ product }: { product: Product }) { const { lines, addToCart, increaseQuantity, decreaseQuantity } = useCart(); const quantity = lines.find((line) => line.productId === product.id)?.quantity ?? 0; const category = categories.find((item) => item.slug === product.category); return <motion.article layout initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="bg-ya-gray border-2 border-ya-gray hover:border-ya-lime"><Link to={'/app/producto/' + product.id} className="block p-4"><div className="h-24 bg-ya-black border-2 border-ya-black flex items-center justify-center text-6xl mb-3">{product.image}</div><p className="text-[10px] uppercase tracking-widest text-ya-lime font-bold">{category?.name}</p><h3 className="font-black leading-tight mt-1 min-h-10">{product.name}</h3><p className="font-black text-lg mt-2">{euro(product.price)}</p></Link>{quantity ? <div className="px-4 pb-4"><QuantitySelector quantity={quantity} onAdd={() => increaseQuantity(product.id)} onRemove={() => decreaseQuantity(product.id)} /></div> : <button onClick={() => addToCart(product.id)} className="m-4 mt-0 w-[calc(100%-2rem)] min-h-11 bg-ya-lime text-ya-black font-black uppercase text-sm hover:bg-white">Añadir</button>}</motion.article>; }
export function CategoryCard({ slug }: { slug: string }) { const category = categories.find((item) => item.slug === slug); if (!category) return null; return <Link to={'/app/categoria/' + category.slug} className="bg-ya-gray border-2 border-ya-gray hover:border-ya-lime p-4 min-h-28 flex flex-col justify-between"><span className="text-3xl">{category.icon}</span><span className="font-black">{category.name}</span></Link>; }
const statusText: Record<OrderStatus, string> = { received:'Pedido recibido', preparing:'Preparando pedido', shopping:'Comprando pedido', ready:'Pedido preparado', delivering:'Ya estoy repartiendo', delivered:'Entregado' };
const statuses = Object.keys(statusText) as OrderStatus[];
export function OrderTimeline({ status }: { status: OrderStatus }) { const active = statuses.indexOf(status); return <ol className="space-y-0">{statuses.map((item,index) => <li key={item} className="flex gap-4 min-h-12"><span className={'w-6 h-6 shrink-0 border-2 text-xs font-black grid place-items-center ' + (index <= active ? 'bg-ya-lime text-ya-black border-ya-lime' : 'border-ya-gray text-gray-500')}>{index < active ? '✓' : index + 1}</span><div><p className={index <= active ? 'font-black' : 'text-gray-500 font-bold'}>{statusText[item]}</p>{index === active && <p className="text-sm text-gray-400">Te avisaremos cuando haya novedades.</p>}</div></li>)}</ol>; }
export function EmptyState({ title, text }: { title: string; text: string }) { return <div className="border-2 border-dashed border-ya-gray p-8 text-center"><PackageOpen className="mx-auto text-ya-lime mb-3" size={36}/><h2 className="font-black text-2xl">{title}</h2><p className="text-gray-400 mt-2">{text}</p></div>; }